version: '3'

services:
  mysql-local-db:
    build:
      context: .
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # This should be changed to the proper folder or any folder of choice on target machine
      - /Users/farayola/Documents/MysqlDataDir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootedmysql"
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - local-db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  phpmyadmin-local:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      PMA_HOST: "mysql-local-db"
    networks:
      - local-db-network
    ports:
      - "9999:80"
    restart: unless-stopped

  redis-local:
    image: redis:5.0
    networks:
      - local-db-network
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  meilisearch-local:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - /Users/farayola/Documents/MeiliSearchDataDir:/data.ms
    networks:
      - local-db-network
    restart: unless-stopped

  mailhog-local:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - local-db-network
    restart: unless-stopped

networks:
  local-db-network:
