version: '3'

services:
  mysql-local-db:
    build:
      context: .
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ${HOME}/DockerData/mysql-data:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # Setting this variable to '%' ensures that the container creates a mysql
      # user (in this case, the root user) with the '%' sign as their host which means
      # they are allowed to connect to the mysql server from ANY host.
      # Not having this will lead to us getting 'cannot connect from xxx host' errors
      # https://github.com/docker-library/mysql/issues/275#issuecomment-292208567
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    restart: unless-stopped
    networks:
      - local-db-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']

  redis-local:
    image: redis:6.0-alpine
    networks:
      - local-db-network
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  meilisearch-local:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - meilisearch-data:/data.ms
    networks:
      - local-db-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  mailhog-local:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - local-db-network
    restart: unless-stopped

 #minio:
 #  image: 'minio/minio:latest'
 #  ports:
 #    - '${FORWARD_MINIO_PORT:-9900}:9000'
 #    - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
 #  environment:
 #    MINIO_ROOT_USER: 'minio'
 #    MINIO_ROOT_PASSWORD: 'password'
 #  volumes:
 #    - minio-data:/data/minio
 #  networks:
 #    - local-db-network
 #  command: minio server /data/minio --console-address ":8900"
 #  healthcheck:
 #    test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
 #    retries: 3
 #    timeout: 5s

  #phpmyadmin-local:
  #  image: phpmyadmin/phpmyadmin:4.8
  #  environment:
  #    PMA_HOST: 'mysql-local-db'
  #  networks:
  #    - local-db-network
  #  ports:
  #    - '9999:80'
  #  restart: unless-stopped

volumes:
  mysql-data:
    name: 'mysql-data-volume'
    driver: local
  redis-data:
    name: 'redis-data-volume'
    driver: local
  meilisearch-data:
    name: 'meilisearch-data-volume'
    driver: local
  minio-data:
    name: 'minio-data-volume'
    driver: local

networks:
  local-db-network:
